describe("Table", ()=> {
  it('should check users table', () => {
    cy.visit('/pages/tables/smart-table')
    cy.get('table').as("table")
    cy.get("@table").should('be.visible')
    cy.get('table [class="ng2-smart-filters ng-star-inserted"] th.ng2-smart-actions-title.ng2-smart-actions-title-add a.ng2-smart-action-add-add').as("addButton")
    cy.get("@addButton").click()
    cy.get('input-editor[class*="ng-star-inserted"] input.form-control[ng-reflect-name="id"]').as("nameInput")
    cy.get("@nameInput").should('be.visible')
    .type('101')
    .should('have.value', '101')
    cy.get('input-editor[class*="ng-star-inserted"] input.form-control[ng-reflect-name="firstName"]').as("firstNameInput")
    cy.get("@firstNameInput").should('be.visible')
      .type('Tanya')
      .should('have.value', 'Tanya')
    cy.get('input-editor[class*="ng-star-inserted"] input.form-control[ng-reflect-name="lastName"]').as("lastNameInput")
    cy.get("@lastNameInput").should('be.visible')
      .type('Maltseva')
      .should('have.value', 'Maltseva')
    cy.get('input-editor[class*="ng-star-inserted"] input.form-control[ng-reflect-name="username"]').as("usernameInput")
    cy.get("@usernameInput").should('be.visible')
      .type('@tmaltseva')
      .should('have.value', '@tmaltseva')
    cy.get('input-editor[class*="ng-star-inserted"] input.form-control[ng-reflect-name="email"]').as("emailInput")
    cy.get("@emailInput").should('be.visible')
      .type('tmaltseva@gmail.com')
      .should('have.value', 'tmaltseva@gmail.com')
    cy.get('input-editor[class*="ng-star-inserted"] input.form-control[ng-reflect-name="age"]').as("ageInput")
    cy.get("@ageInput").should('be.visible')
      .type('28')
      .should('have.value', '28')
    cy.get('table td.ng2-smart-actions.ng-star-inserted a.ng2-smart-action-add-create').as("createButton")
    cy.get("@createButton").click()
    cy.get('table td.ng2-smart-actions.ng-star-inserted a.ng2-smart-action-edit-edit').first().as("editButton")
    cy.get("@editButton").click()
    cy.get("@firstNameInput").should('be.visible')
    cy.get('input-editor[class*="ng-star-inserted"] input.form-control[ng-reflect-name="firstName"]').clear()
      .type('Anna')
      .should('have.value', 'Anna')
    cy.get('table td.ng2-smart-actions.ng-star-inserted a.ng2-smart-action-edit-save').as("editSaveButton")
    cy.get("@editSaveButton").click()
    cy.get('table tbody tr:nth-of-type(1)>td:nth-of-type(3)').as("firstNameInputEdit")
    cy.get("@firstNameInputEdit").should('have.text', "Anna")
});
})
